set updatetime=160

set encoding=utf-8

set confirm

set hidden

set lazyredraw

set wildmenu

set guifont=Menlo-Regular:h13

set guicursor+=a:blinkon0

set belloff=all

set number

set ruler

set laststatus=2

set cmdheight=1

syntax enable

set spell

set linebreak

set scrolloff=1

set sidescrolloff=1

set nofoldenable

set tabstop=4

set softtabstop=4

set shiftwidth=4

set expandtab

set incsearch

set hlsearch

set ignorecase

set smartcase

set showmatch

set mps+=<:>

Plug 'dominikduda/vim_current_word'

Plug 'chrisbra/Colorizer'
nnoremap <leader>c :ColorToggle<CR>

Plug 'luochen1990/rainbow'
let g:rainbow_active = 1

Plug 'airblade/vim-gitgutter'

Plug 'sheerun/vim-polyglot'

Plug 'iamcco/markdown-preview.nvim', {'do': 'cd app && yarn install'}
nnoremap <leader>m :MarkdownPreview<CR>
let g:mkdp_refresh_slow=1
